03_Django/Pari-programming-2/articles/urls.py
from django.urls import path
from . import views

app_name ='articles'

urlpatterns = [
    path('', views.index , name='index'),
    path('create/', views.create, name='create' ),
    path('<int:article_pk>/detail/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/likearticle/', views.likearticle, name='likearticle'),
    
]

03_Django/Pari-programming-2/articles/models.py
from django.db import models
from django.conf import settings

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_articles", blank=True)
    class Meta:
        ordering =('-pk',)

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    class Meta:
        ordering=('-pk',)

03_Django/Pari-programming-2/articles/forms.py
from django.forms import ModelForm
from articles.models import Article, Comment

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content',]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]
    

03_Django/Pari-programming-2/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.views.decorators.http import require_POST
from IPython import embed

def index(request):
    articles = Article.objects.all()
    # embed()
    context = {'articles':articles,}
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context= {'form': form,}
    return render(request, 'articles/forms.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk= article_pk)
    # embed()
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context ={'article':article, 'comments':comments, 'comment_form':comment_form, }
    return render(request, 'articles/detail.html', context)

@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk= article_pk)
    article.delete()
    return redirect('articles:index')

def update(request, article_pk):
    article = get_object_or_404(Article, pk= article_pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance= article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article_pk)
    else:
        form = ArticleForm(instance= article)
    context= {'form': form,}
    return render(request, 'articles/forms.html', context)

@require_POST
def comment_create(request, article_pk):
    comment = CommentForm(request.POST).save(commit=False)
    comment.article_id = article_pk
    comment.save()
    return redirect('articles:detail', article_pk)

@require_POST
def comment_delete(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)

def likearticle(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    # embed()

    if article.like_users.filter(pk=request.user.id):
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
        
    
    return redirect('articles:detail', article_pk)

03_Django/Pari-programming-2/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>detail</h1>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <p>작성 시간 : {{ article.created_at }}</p>
    <p>수정 시간: {{ article.updated_at }}</p>
    
    <hr>
    {% for comment in comments %}
        <p>{{comment.pk}}번째 댓글 : {{ comment.content }}</p>
        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value='댓글삭제' >
        </form>
    {% empty%}
        <p> 없 -----------음 </p>
    {% endfor %}
        <form action="{% url 'articles:comment_create' article.pk %}" method="POST">
                {% csrf_token %}
                {{ comment_form }}
                <input type="submit" value='submit'>
        </form>
    <hr>

    <hr>
    <a href="{% url  'articles:index' %}" class = 'btn btn-danger'>[메인페이지]</a>
    <a href="{% url 'articles:update' article.pk %}" class ='btn btn-primary'>[글 수정]</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글삭제">
    </form>
    
{% endblock %}

03_Django/Pari-programming-2/articles/templates/articles/forms.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

{% endblock %}

03_Django/Pari-programming-2/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
<h1> Article </h1>
{% for article in articles %}
<h3>{{ article.pk }}번째 {{ article.title }} </h3>
<h3>{{ article.content }}</h3>
<p>{{ article.like_users.count }}명이 이 글을 좋아합니다!</p>
<a href="{% url 'articles:likearticle' article.pk %}">좋아요</a>
<hr>
<a href="{% url 'articles:detail' article.pk %}" class='btn btn-info'>[상세글 보기]</a>
{% endfor %}
<hr>
<a href="{% url 'articles:create'  %}" class='btn btn-success'>[글작성]</a>
{% endblock %}