03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'), # GET
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'), # GET 작성, POST 생성
    path('<int:article_pk>/', views.detail, name='detail'), # GET
    path('<int:article_pk>/delete/', views.delete, name='delete'), # POST
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'), # GET 수정, POST 업데이트
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'제목: {self.title}, 내용: {self.content}'
        

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk', ]
    
    def __str__(self):
        return f'댓글: {self.content}'

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from .models import Article, Comment
from IPython import embed

def index(request):
    articles = Article.objects.order_by('-pk')
    # print(articles)
    # print(type(articles))
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)
# Create your views here.

# def new(request):
#     embed()
#     return render(request, 'articles/new.html')

def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article(title=title, content=content)
        article.full_clean()
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        return render(request, 'articles/create.html')

    # try:
    #     title = request.POST.get('title')
    #     content = request.POST.get('content')
    #     article = Article(title=title, content=content)
    #     article.full_clean()
    # except ValidationError:
    #     raise ValidationError('Your Error Message')
    # else:
    #     article.save()
    #     return redirect('articles:detail', article.pk)



    # 1번째 방법
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # # 2번째 방법
    # article = Article(title=title, content=content)
    # article.save()

    # # 3번째 방법
    # Article.objects.create(title=title, content=content)
    
    # return redirect('/articles/'+str(article.pk))
    #return redirect('article/')로 입력하면 create 뒤에 추가로 article이 붙은상태
    #그걸 막기 위해서 /를 앞에 붙인다.

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == "POST":
        article.delete()
        return redirect('articles:index')
    else:
        context = {'article': article}
        return render(request, 'articles/detail.html', context)

# def edit(request, pk):
#     article = Article.objects.get(pk=pk)
#     context = {'article': article}
#     return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'GET':
        context = {'article': article}
        return render(request, 'articles/edit.html', context)
    else:
        # embed()
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('articles:detail', article.pk)


def comments_create(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    res = request.POST.get('content')
    if request.method == 'POST':
        comment = Comment()
        comment.content = res
        comment.article = article
        comment.save()
        return redirect('articles:detail', article.pk)


    else:
        return redirect('articles:detail', article.pk)

        
def comment_delete(request, article_pk, comment_pk):
    if request.method == 'POST':
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
    return redirect('articles:detail', article_pk)


def comment_update(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('articles:detail', article_pk)
    else:
        context = {
            'comment': comment,
        }
        return render(request, 'articles/comment_update.html', context)

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/templates/articles/comment_update.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="post">
    <label for="content">댓글</label>
    <textarea name="content" id="content" cols="30" rows="10">{{ comment.content }}</textarea>
    <input type="submit" value="댓글 수정">
</form>

{% endblock %}

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block body %}
    <h2 class="text-center">NEW</h2>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" name="title" id="title"><br>
        <label for="content">Content</label>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
        <input type="submit" value="글 작성">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">메인페이지</a>
{% endblock %}

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">DETAIL</h2>
    <h3>{{ article.pk }}</h3>
    <hr>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <p>글 생성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
    <p>글 수정 시각: {{ article.updated_at|date:"M j Y" }}</p>
    <hr>
    <p><b>{{ article.comments.all|length }}개의 댓글</b></p>
    {% for comment in article.comments.all %}
        <li>
        <p>댓글 번호: {{ comment.id }}</p>
        <p>댓글 내용: {{ comment.content}}</p>
        </li>
        <form action="{% url 'articles:comment_delete' article.pk comment.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="댓글 삭제">
        
        </form>
        <a href="{% url 'articles:comment_update' article.pk comment.pk %}">댓글 수정</a>
        {% empty %}
            <p><b>댓글이 없습니다. 댓글을 작성해주세요.</b></p>
    {% endfor %}

    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
        {% csrf_token %}
        <label for="content">comment</label><br>
        <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
        <input type="submit" value="댓글 작성" class="btn btn-warning">

    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[메인 페이지]</a><br>
    <a href="{% url 'articles:update' article.pk %}">[글 수정]</a><br>
    <form action="{% url 'articles:delete' article.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="글 삭제">

    </form>
{% endblock %}

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block body %}
    <h2 class="text-center">NEW</h2>
    
    <form action="{% url 'articles:update' article.pk %}" method="POST">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" name="title" id="title" value="{{ article.title }}"><br>
        <label for="content">Content</label>
        <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
        <input type="submit" value="글 수정">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">메인페이지</a>
{% endblock %}

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">Articles</h2>
    {% for article in articles %}
        <p>글 번호: {{article.id}}</p>
        <p>글 제목: {{article.title}}</p>
        <a href="{% url 'articles:detail' article.pk %}">[상세 글]</a>
    {% endfor %}
    <br>
    <a href="{% url 'articles:create' %}">글 작성</a>
{% endblock %}

03_Django/04_django_crud_review - 복사본(이미지 실습 전)/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block body %}
    <h2 class="text-center">NEW</h2>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title</label>
        <input type="text" name="title" id="title"><br>
        <label for="content">Content</label>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
        <input type="submit" value="글 작성">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">메인페이지</a>
{% endblock %}